version: '3.8'

services:
  clientmanagement-web:
    build:
      context: .
      dockerfile: VeconinterTechnicalTest.Web/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sqlserver
    env_file:
      - .env
    networks:
      - clientmanagement-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - clientmanagement-network

networks:
  clientmanagement-network:
    driver: bridge

volumes:
  sqlserver_data:
